<#
.SYNOPSIS
    Expose the local dev stack through an ngrok tunnel and wire the public host
    into the files Sanctum needs.

.DESCRIPTION
    Sanctum cookie auth is origin-locked, so a bare `ngrok http 5173` leaves the
    SPA in a 419/401 loop. This script:

      1. locates ngrok (PATH, then the winget package, then %LOCALAPPDATA%\Programs),
      2. reuses a running agent or starts `ngrok http <Port>`, then reads the
         public URL from ngrok's local API (http://127.0.0.1:4040),
      3. writes frontend/.env.ngrok (VITE_API_URL=, VITE_TUNNEL_HOST, VITE_DEV_PORT),
      4. rewrites the ngrok host in backend/.env SANCTUM_STATEFUL_DOMAINS,
      5. prints the URL and the commands to run next.

    Vite must be running in tunnel mode for the same-origin API proxy to exist:
        cd frontend; npm run dev:ngrok

    A free account is assigned one domain and the agent reclaims it on restart,
    but this script rewrites both files on every run in case ngrok hands out a
    different one. Use -Stop to shut the agent down again.

.PARAMETER Port
    Local port to expose. Defaults to 5174, i.e. the `dev:ngrok` Vite instance,
    so a normal `npm run dev` on 5173 keeps working untouched.

.PARAMETER Stop
    Stop the running ngrok agent and exit.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File tools/ngrok-dev.ps1
    powershell -ExecutionPolicy Bypass -File tools/ngrok-dev.ps1 -Stop
#>
[CmdletBinding()]
param(
    [int]$Port = 5174,
    [switch]$Stop
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$apiUrl = 'http://127.0.0.1:4040/api/tunnels'

function Get-NgrokPath {
    $onPath = Get-Command ngrok.exe -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }

    $candidates = @("$env:LOCALAPPDATA\Programs\ngrok\ngrok.exe")
    $candidates += Get-ChildItem "$env:LOCALAPPDATA\Microsoft\WinGet\Packages" `
        -Filter 'ngrok.exe' -Recurse -Depth 2 -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty FullName

    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path $candidate)) { return $candidate }
    }
    throw 'ngrok.exe not found. Install it with `winget install Ngrok.Ngrok` or from https://ngrok.com/download.'
}

function Get-TunnelHosts {
    try {
        return @((Invoke-RestMethod $apiUrl -TimeoutSec 5).tunnels)
    } catch {
        return @()
    }
}

$agents = @(Get-Process ngrok -ErrorAction SilentlyContinue)

if ($Stop) {
    if (-not $agents) { Write-Host 'No ngrok agent is running.'; exit 0 }
    $agents | Stop-Process -Force
    Write-Host "Stopped ngrok (pid $($agents.Id -join ', '))." -ForegroundColor Yellow
    Write-Host 'The tunnel host stays in backend/.env; that is harmless locally, so remove it only when convenient.'
    exit 0
}

$tunnels = Get-TunnelHosts

if (-not $tunnels) {
    if ($agents) {
        throw "'ngrok' is running but its API on 127.0.0.1:4040 did not answer. Restart the agent (tools/ngrok-dev.ps1 -Stop) and try again."
    }

    $ngrok = Get-NgrokPath
    Write-Host "Starting tunnel: ngrok http $Port  (agent $((& $ngrok version) -replace 'ngrok version ', ''))"
    Start-Process -FilePath $ngrok `
        -ArgumentList "http $Port --log=stdout --log-format=logfmt" `
        -RedirectStandardOutput "$env:TEMP\ngrok-agent.out" `
        -RedirectStandardError "$env:TEMP\ngrok-agent.err" `
        -WindowStyle Hidden

    for ($attempt = 1; $attempt -le 20 -and -not $tunnels; $attempt++) {
        Start-Sleep -Milliseconds 750
        $tunnels = Get-TunnelHosts
    }
    if (-not $tunnels) {
        $err = Get-Content "$env:TEMP\ngrok-agent.err" -Tail 15 -ErrorAction SilentlyContinue
        throw "ngrok did not publish a tunnel. Agent stderr:`n$err"
    }
}

$http = $tunnels | Where-Object { $_.proto -eq 'https' -and $_.public_url } | Select-Object -First 1
if (-not $http) { throw 'No https tunnel found in the ngrok agent API response.' }

$publicUrl = $http.public_url.TrimEnd('/')
$hostName = $publicUrl -replace '^https?://', ''
$target = $http.config.addr

$ngrokEnv = @(
    '# Generated by tools/ngrok-dev.ps1: local + gitignored; rewritten on each run.',
    '# VITE_API_URL must stay empty: relative /api and /sanctum requests go through',
    '# the dev-server proxy so the Sanctum cookie stays first-party (see vite.config.js).',
    'VITE_API_URL=',
    "VITE_TUNNEL_HOST=$hostName",
    "VITE_DEV_PORT=$Port"
) -join "`n"
[IO.File]::WriteAllText((Join-Path $root 'frontend/.env.ngrok'), "$ngrokEnv`n")

$envPath = Join-Path $root 'backend/.env'
$envText = [IO.File]::ReadAllText($envPath)
$pattern = '(?m)^SANCTUM_STATEFUL_DOMAINS=(.*)$'
if ($envText -notmatch $pattern) { throw 'SANCTUM_STATEFUL_DOMAINS not found in backend/.env.' }

$kept = @($Matches[1].Split(',') |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ -and $_ -notmatch 'ngrok-free\.(app|dev)$|trycloudflare\.com$' })
$stateful = (@($kept) + $hostName) -join ','
[IO.File]::WriteAllText($envPath, [regex]::Replace($envText, $pattern, "SANCTUM_STATEFUL_DOMAINS=$stateful"))

Write-Host ''
Write-Host "Tunnel   : $publicUrl  ->  $target" -ForegroundColor Green
Write-Host "Cookie   : SANCTUM_STATEFUL_DOMAINS=$stateful"
Write-Host "Env file : frontend/.env.ngrok (VITE_TUNNEL_HOST=$hostName)"
Write-Host ''
Write-Host 'Next:'
Write-Host '  cd frontend; npm run dev:ngrok      # if Vite is not running yet'
Write-Host "  open $publicUrl/login               # first visit shows ngrok's interstitial: click Visit Site once"
Write-Host ''
Write-Host "Mobile (Expo) can point at the same host: EXPO_PUBLIC_API_URL=$publicUrl"
Write-Host 'Stop the tunnel with: powershell -ExecutionPolicy Bypass -File tools/ngrok-dev.ps1 -Stop'
